/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qrcodegenerator.ui;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;

/**
 *
 * @author RESEARCH2
 */
public class JPanelColorScheme extends javax.swing.JPanel {

    /**
     * Creates new form JPanelColorScheme
     *
     * @param comp
     */
    public JPanelColorScheme(Component comp) {
        initComponents();
        //this.setLocation(comp.getLocation());
        jButtonColor1.setName("color_1");
        jButtonColor2.setName("color_2");
        jButtonColor3.setName("color_3");
        jButtonColor4.setName("color_4");
        addColorSchemeBtnListener();
    }

    /**
     * Gets this class
     *
     * @return
     */
    public JPanelColorScheme getJPanelColorScheme() {
        return this;
    }

    /**
     * Add action listener to all buttons in the color scheme panel
     *
     * @param al
     */
    public void addBtnActionListener(ActionListener al) {
        for (Component compo : this.getComponents()) {
            if (compo instanceof JButton) {
                JButton jbtn = (JButton) compo;
                jbtn.addActionListener(al);
            }
        }
    }

    /**
     * *
     * Add mouse listener for all the buttons on the top panel
     *
     */
    public final void addColorSchemeBtnListener() {
        for (Component comp : this.getComponents()) {
            if (comp instanceof JButton) {
                JButton jbtn = (JButton) comp;
                jbtn.addMouseListener(new MouseAdapter() {

                    @Override
                    public void mouseEntered(MouseEvent e) {
                       JButton jbtn = (JButton) e.getComponent();
                       jbtn.setOpaque(true);
                       repaint();
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                       JButton jbtn = (JButton) e.getComponent();
                       jbtn.setOpaque(false);
                       repaint();
                    }
                });
            }

        }
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonColor1 = new javax.swing.JButton();
        jButtonColor2 = new javax.swing.JButton();
        jButtonColor3 = new javax.swing.JButton();
        jButtonColor4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 0));

        jButtonColor1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jButtonColor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qrcodegenerator/resources/scheme_1.png"))); // NOI18N
        jButtonColor1.setText("Color Scheme 1");
        jButtonColor1.setBorderPainted(false);
        jButtonColor1.setContentAreaFilled(false);
        jButtonColor1.setFocusable(false);

        jButtonColor2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jButtonColor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qrcodegenerator/resources/scheme_3.png"))); // NOI18N
        jButtonColor2.setText("Color Scheme 2");
        jButtonColor2.setBorderPainted(false);
        jButtonColor2.setContentAreaFilled(false);
        jButtonColor2.setFocusable(false);

        jButtonColor3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jButtonColor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qrcodegenerator/resources/scheme_2.png"))); // NOI18N
        jButtonColor3.setText("Color Scheme 3");
        jButtonColor3.setBorderPainted(false);
        jButtonColor3.setContentAreaFilled(false);
        jButtonColor3.setFocusable(false);

        jButtonColor4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jButtonColor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qrcodegenerator/resources/scheme_4.png"))); // NOI18N
        jButtonColor4.setText("Color Scheme 4");
        jButtonColor4.setBorderPainted(false);
        jButtonColor4.setContentAreaFilled(false);
        jButtonColor4.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonColor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonColor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonColor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonColor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonColor1, jButtonColor2, jButtonColor3, jButtonColor4});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonColor1;
    private javax.swing.JButton jButtonColor2;
    private javax.swing.JButton jButtonColor3;
    private javax.swing.JButton jButtonColor4;
    // End of variables declaration//GEN-END:variables
}
